### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by caecos** [MarcBoule/Geodesics#1]
Here's the latest binary release of Geodesics, compiled against the latest Rack's sources. I'll will keep the binary updated until they are incorporated in the plugins managers.

[Geodesics-0.6.0-win.zip](https://github.com/MarcBoule/Geodesics/files/2246387/Geodesics-0.6.0-win.zip)

**Comment by MarcBoule** [comment]
The builds for all platforms were just added in the release section.
https://github.com/MarcBoule/Geodesics/releases/tag/0.6.0
Thanks for the offer regarding the win build, but if anything comes up, I will update the release section with new builds for all platforms, until it is released and entered into the plugin manager.
