### ISSUE TITLE
Torus request: invert signal below

### ISSUE THREAD

**Issue by glocke01** [MarcBoule/Geodesics#1]
I suggest an option (right click menu or toggle) that inverts the signals of torus inputs for outputs below the input. This would mainly by useful for CV, although I can imagine some phase cancellation effects that might come about with audio. 

One of my favorite things about Torus is its ability to create interesting combinations of multiple CV inputs. This option would increase the variation quite a bit.

**Comment by MarcBoule** [comment]
We'll take a look at this option, and we will let you know when it's ready. It will likely take a while until the next update, but we can provide a build for testing if ever you are still interested. Thanks for the suggestion!

**Comment by MarcBoule** [comment]
I don't think we will be implementing this finally, sorry.
