### ISSUE TITLE
Latest build fails in Debian

### ISSUE THREAD

**Issue by tank-trax** [MarcBoule/Geodesics#10]
Building on Debian 9.9 on the latest Rackv1.dev.4b3508b

when trying to run Rack with Geodesics

```
./Rack 
Rack: src/plugin/Plugin.cpp:17: void rack::plugin::Plugin::addModel(rack::plugin::Model*): Assertion `isSlugValid(model->slug)' failed.
Aborted
```

same issue with DHE-Modules and ImpromptuModular

**Comment by MarcBoule** [comment]
Fixed in latest commit, thanks! :-)
