### ISSUE TITLE
Wrong parameter tooltip on Energy

### ISSUE THREAD

**Issue by stoermelder** [MarcBoule/Geodesics#11]
Just a minor thing, should be "Freq C":
https://github.com/MarcBoule/Geodesics/blob/4dac1c7718f4a95ff05fb87891b5bfeeead7898d/src/Energy.cpp#L87

**Comment by MarcBoule** [comment]
Thanks for spotting that, fixed in https://github.com/MarcBoule/Geodesics/commit/cfb693badf18b41538a07d5ef9b7fee4c504889d
Cheers!
