### ISSUE TITLE
Torus should have cv input to cycle through the 7 outputs. 

### ISSUE THREAD

**Issue by modman2019** [MarcBoule/Geodesics#12]
I used pulsars to do this fine, but what if torus had a cv input - then it would be more compact.

**Comment by MarcBoule** [comment]
Thanks for the suggestion, I have passed it on to Pyer who desined the modules graphics and concept, but I'm not sure that it will fall within the scope of what was wanted for this small module. We'll see! Cheers :-)

**Comment by MarcBoule** [comment]
After speaking with Pyer, this idea is unfortunately not going to make it in Torus, so I guess we can put it in the Torus2 file for later ;-)
