### ISSUE TITLE
FR: CV control for Ions

### ISSUE THREAD

**Issue by davephillips** [MarcBoule/Geodesics#2]
I'd love to control the Energy settings for Ions via CV. Actually, I'd like control everything in your modules via CV input. :) 

Wonderful modules, thank you for sharing them.

**Comment by MarcBoule** [comment]
Thanks Dave, duly noted, I'll pass the suggestion along to Pyer 👍

**Comment by MarcBoule** [comment]
Addressed in Geodesics 0.6.1, which should now be final and ready to be included in plugin manager imminently.
