### ISSUE TITLE
current fail on build 

### ISSUE THREAD

**Issue by shreeswifty** [MarcBoule/Geodesics#3]
src/BlackHoles.cpp: In constructor ‘BlackHolesWidget::BlackHolesWidget(BlackHoles*)’:
src/BlackHoles.cpp:321:12: error: ‘createLightCentered’ was not declared in this scope
   addChild(createLightCentered<SmallLight<GeoWhiteLight>>(Vec(34.5f, 178.5f), module, BlackHoles::EXP_LIGHTS + 0));
            ^
src/BlackHoles.cpp:321:56: error: expected primary-expression before ‘>’ token
   addChild(createLightCentered<SmallLight<GeoWhiteLight>>(Vec(34.5f, 178.5f), module, BlackHoles::EXP_LIGHTS + 0));
                                                        ^
src/BlackHoles.cpp:321:112: warning: right operand of comma operator has no effect [-Wunused-value]
   addChild(createLightCentered<SmallLight<GeoWhiteLight>>(Vec(34.5f, 178.5f), module, BlackHoles::EXP_LIGHTS + 0));
                                                                                                                ^
src/BlackHoles.cpp:353:56: error: expected primary-expression before ‘>’ token
   addChild(createLightCentered<SmallLight<GeoWhiteLight>>(Vec(129.5f, 201.5f), module, BlackHoles::EXP_LIGHTS + 1));
                                                        ^
src/BlackHoles.cpp:353:113: warning: right operand of comma operator has no effect [-Wunused-value]
   addChild(createLightCentered<SmallLight<GeoWhiteLight>>(Vec(129.5f, 201.5f), module, BlackHoles::EXP_LIGHTS + 1));
                                                                                                                 ^
../../compile.mk:64: recipe for target 'build/src/BlackHoles.cpp.o' failed
make: *** [build/src/BlackHoles.cpp.o] Error 1

**Comment by MarcBoule** [comment]
Can you check that you have the code below at the end of the `include/helpers.hpp` file in your Rack sources:
```
template <class TModuleLightWidget>
TModuleLightWidget *createLightCentered(Vec pos, Module *module, int firstLightId) {
	TModuleLightWidget *light = new TModuleLightWidget();
	light->box.pos = pos.minus(light->box.size.div(2));
	light->module = module;
	light->firstLightId = firstLightId;
	return light;
}
```
If not, then your pull might not have worked properly.
