### ISSUE TITLE
v1 branch builds & loads

### ISSUE THREAD

**Issue by davephillips** [MarcBoule/Geodesics#7]
Fedora 23 Linux
Rack v1.dev.357952c

Hey guys ! :) Just a quick note of praise for the work you've done getting the Impromptu and Geodesics plugins in shape for Rack v1. The plugins are building, loading, and running fine in my small tests so far. I'll continue to test and will report any anomalies. As always, thank you so much for providing the community with some of the finest modules for our beloved VCV Rack. :)

**Comment by MarcBoule** [comment]
Thanks Dave! Very much appreciate the kind words :-) 
There's a small bug in Foundry that I need to fix (SEQ knob doesn't work in SEQ mode), but other than that, any testing and bug reports will be so much appreciated. 
Cheers!
