### ISSUE TITLE
BUG: Branes Lower toggles ±5v and 0-1v, not ±1v and 0-1v as labeled

### ISSUE THREAD

**Issue by patman023** [MarcBoule/Geodesics#8]
![image](https://user-images.githubusercontent.com/36520477/56242439-86b4e700-6055-11e9-9c95-9316f4a29a32.png)

![image](https://user-images.githubusercontent.com/36520477/56242456-8fa5b880-6055-11e9-86f8-c914f5e9edd7.png)

**Comment by MarcBoule** [comment]
I think you might be misunderstanding the use of the button. Here is the main idea:
* When the lights are off, all outputs (upper and lower brane) are -5/+5V by default. 
* When the top-left light is on there is no change for the three top-left outputs (i.e. they stay -5/+5V) but the four others become 0/10V. 
* When the bottom left light is on, the three bottom-left outputs become -1/+1V and the four others become 0/1V.
This seems consistent also with the 0.6.6 manual.

**Comment by patman023** [comment]
gotcha. this wasn't intuitive right off the bat for me. now that the manual is confirmed working though, maybe i'll RTFM first :-P
