### ISSUE TITLE
build error on v1

### ISSUE THREAD

**Issue by davephillips** [MarcBoule/Geodesics#9]
Fedora 23 Linux
Rack v1.dev.26abab6

Hi Marc ! Got a problem building Geodesics this morning:

src/Torus.cpp:40:8: error: ‘f32_4’ in namespace ‘rack::simd’ does not name a type
  simd::f32_4 b1 = simd::f32_4(0.0f);
        ^
src/Torus.cpp:41:8: error: ‘f32_4’ in namespace ‘rack::simd’ does not name a type
  simd::f32_4 lowout = simd::f32_4(0.0f);
        ^
src/Torus.cpp: In member function ‘void QuadOnePoleFilter::setCutoff(int, float)’:
src/Torus.cpp:47:3: error: ‘b1’ was not declared in this scope
   b1.store(tb1);
   ^
src/Torus.cpp:49:14: error: ‘rack::simd::f32_4’ has not been declared
   b1 = simd::f32_4::load(tb1);
              ^
src/Torus.cpp: In member function ‘void QuadOnePoleFilter::process(float*)’:
src/Torus.cpp:53:3: error: ‘f32_4’ is not a member of ‘rack::simd’
   simd::f32_4 lastin = simd::f32_4::load(inflt);
   ^
src/Torus.cpp:54:3: error: ‘lowout’ was not declared in this scope
   lowout = lastin * (1.0f - b1) + lowout * b1;
   ^
src/Torus.cpp:54:12: error: ‘lastin’ was not declared in this scope
   lowout = lastin * (1.0f - b1) + lowout * b1;
            ^
src/Torus.cpp:54:29: error: ‘b1’ was not declared in this scope
   lowout = lastin * (1.0f - b1) + lowout * b1;
                             ^
src/Torus.cpp: At global scope:
src/Torus.cpp:97:8: error: ‘f32_4’ in namespace ‘rack::simd’ does not name a type
  simd::f32_4 xstate = simd::f32_4(0.0f);
        ^
src/Torus.cpp:98:8: error: ‘f32_4’ in namespace ‘rack::simd’ does not name a type
  simd::f32_4 ystate = simd::f32_4(0.0f);
        ^
src/Torus.cpp: In member function ‘void QuadRCFilter::process(float*)’:
src/Torus.cpp:107:3: error: ‘f32_4’ is not a member of ‘rack::simd’
   simd::f32_4 c = simd::f32_4::load(cutoffs);
   ^
src/Torus.cpp:108:3: error: ‘f32_4’ is not a member of ‘rack::simd’
   simd::f32_4 x = simd::f32_4::load(x_f);
   ^
src/Torus.cpp:109:3: error: ‘f32_4’ is not a member of ‘rack::simd’
   simd::f32_4 y = (x + xstate - ystate * (1.0f - c)) / (1.0f + c);
   ^
src/Torus.cpp:110:3: error: ‘xstate’ was not declared in this scope
   xstate = x;
   ^
src/Torus.cpp:110:12: error: ‘x’ was not declared in this scope
   xstate = x;
            ^
src/Torus.cpp:111:3: error: ‘ystate’ was not declared in this scope
   ystate = y;
   ^
src/Torus.cpp:111:12: error: ‘y’ was not declared in this scope
   ystate = y;
            ^
../../compile.mk:61: recipe for target 'build/src/Torus.cpp.o' failed
make: *** [build/src/Torus.cpp.o] Error 1
make: *** Waiting for unfinished jobs....

Any suggestions ?

**Comment by MarcBoule** [comment]
Looks like Andrew made some changes to his SIMD code in Rack, since this was working yesterday, but it's failing on my end also after pulling the latest Rack v1 source. I should have time to make the adjustments today :-) Thanks!

**Comment by MarcBoule** [comment]
Should be fixed now with https://github.com/MarcBoule/Geodesics/commit/3fbb545a16e1a989524c62905558c4c78687c1e8
Cheers Dave!
